### ISSUE TITLE
Redundant property currentTrip and IsAvailable.

### ISSUE THREAD

**Issue by amarlearning** [anomaly2104/lld-cab-booking-ola-uber-grab-lyft#1]
I have a small doubt, even if we have just one property like `currentTrip` with that we check the status of the trip and we use that to get to know whether the driver is available or not.

https://github.com/anomaly2104/lld-cab-booking-ola-uber-grab-lyft/blob/bc4c18ae6aca9836b3e060779edb4ebb678a8c64/src/main/java/com/uditagarwal/cabbooking/model/Cab.java#L11-L14

So, I think there is no need to have this class attribute `isAvailable`. But yes we can have a getter method, which can tell whether a cab is available using the `currentTrip` attribute.

For example:
```java
public boolean isAvailable() {
	return this.currentTrip == null;
}
```

Let me know your thoughts on this.

**Comment by anomaly2104** [comment]
HI @amarlearning,
You have raised a good point. Actually, now I feel I have used a very bad name for this attribute. This attibute actually tells whether the cab is actually on or not. I think a better name would have been something like `isDeviceOn`. 

Convenience method we can definitely have. It will become something like:
```
public boolean isAvailable() {
	return isDeviceOn && this.currentTrip == null;
}
```

**Comment by amarlearning** [comment]
Ok. I got it now. Thanks
